const RouteName = {
    SPLSH: "SplashScreen",
    // TAB_HOME : "Home",
    SWIPER_SCREEN : "Swiperscreen",
    LOGIN_SCREEN : "LoginScreen",
    REGISTER_SCREEN : "Register",
    OTP_VERYFY_SCREEN: 'OtpVeryfiveScreen', 
    HOME_SCREEN : "HomeScreen",
    REGIATRAION_SUCCESSFULL : "RegistrationSuccessful",    
    POPULAR_TAB: "Popular",
    BEST_TAB_SET : "Bets",
    HISTORYS_TAB : "History",
    HOMES_TAB : "Homes",
    PROFILE_TAB : "Profile", 
    ADD_MEETING_SCREEN: "AddMeetingScreen",
    ADD_TASK_SCREEN: "AddTaskScreen",
    ADD_CALL_SCREEN: "AddCallScreen",
    TAKS_SCREEN: "TaskScreen",
    HOME_TAB_SEARCH_SCREEN: "HomeTabSearchScreen",
    SELECT_MODULES_SCREEN: "SelectModuleSearch" ,
    FEED_BACK_SCREEN: "DraweFeedback",
    NEW_LEADS_SCREEN: "NewLeadsScreen",
    FEED_BACK_SCREEN: "DraweFeedback",
    SETTINGS_SCREEN: "DrawerSettings",
    UNSYNCEDRECORD_SCREEN: "DrawerUnsyncedRecords",
    DRAWERPARTI_CULARTABSCREEN: "DrawerParticularTasks",
    TASK_DETAILS_SCREEN: "TaskDetailsScreen",
    DRAWER_MEETINGS: "DrawerMeeting",
    DRAWER_LEAD_MAP: "DrawerLeadMap",
    EsportsScreen: "DrawerEsport",
    SPORTS_SCREEN: "DrawerSport",
    BASKETBALLSCREEN: "DrawerBasketBall",
    COUNTRY_MATCH_SCREEN: "DrawerCountryVsMatch",
  
}
export default RouteName;