import { Colors, Fonts, SF, SH, SW, widthPercent, } from '../../utils';
import { StyleSheet, Dimensions } from 'react-native';

export default StyleSheet.create({
  Margintopspace: {
    marginTop: 80,
    flexDirection: 'row',
    justifyContent: 'center'
  },
  Setcountryflexview: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 20,
    justifyContent: 'center',
    width: '100%',
  },
  Goldcoinsstyle: {
    height: 40,
    width: 40,
    position: 'absolute',
    left: 0,
    top: 3,
  },
  Firstgameanimation: {
    height: 200,
    width: 200,
  },
  Indiaflaganimation: {
    height: 35,
    width: 35,
    position: 'absolute',
    left: 0,
    top: 3,
  },
  Indiaflaganimationtwo: {
    height: 35,
    width: 35,
    position: 'absolute',
    left: -4,
    top: 3,
    marginLeft: 10,
  },
  Lotteviewsetstyle: {
    height: 50,
    width: 50,
  },
  countrytextstyle: {
    color: Colors.White_text_color,
    fontSize: 18,
    fontFamily: Fonts.Poppins_Medium,
    marginRight: 10,
    marginTop: 5,
  },
  countrytextstyletwo: {
    color: Colors.White_text_color,
    fontSize: 13,
    fontFamily: Fonts.Poppins_Medium,
    marginTop: 0,
  },
  Setminboxviewstyle: {
    marginTop: 30,
    backgroundColor: Colors.Commonheaderlinergradiunttwo,
    width: '90%',
    paddingBottom: 20,
    padding: 10,
    borderRadius: 10,
  },
  FlexrowCountry: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  Indiatextsflex: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  diffenttimeset: {
    color: Colors.White_text_color,
    fontSize: 19,
    paddingBottom: 4,
    fontWeight: '700',
    fontFamily: Fonts.Poppins_Medium,
  },
  Resultswinviews: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  Setboxcolorview: {
    backgroundColor: Colors.light_gray_text_color,
    width: widthPercent(25),
    height: 25,
    borderRadius: 7,
    flexDirection: 'row',
    alignItems: 'center',
  },
  Setboxcolorviewgold: {
    backgroundColor: Colors.Gold_text_color,
    width: widthPercent(25),
    height: 25,
    borderRadius: 7,
    flexDirection: 'row',
    alignItems: 'center',
  },
  Setboxcolorviewtwo: {
    backgroundColor: Colors.light_gray_text_color,
    width: widthPercent(40),
    height: 25,
    borderRadius: 7,
    flexDirection: 'row',
    alignItems: 'center',
  },
  Setboxcolorviewgoldtwo: {
    backgroundColor: Colors.Gold_text_color,
    width: widthPercent(40),
    height: 25,
    borderRadius: 7,
    flexDirection: 'row',
    alignItems: 'center',
  },
  Wintextstylset: {
    color: Colors.black_text_color,
    fontSize: 12,
    marginLeft: 10,
    marginRight: 10,
    paddingRight: 7,
    borderStyle: 'dashed',
    borderRightWidth: 1,
    borderRightColor: Colors.black_text_color,
    fontFamily: Fonts.Poppins_Medium,
  },
  Wintextstylsettwo: {
    color: Colors.black_text_color,
    fontSize: 12,
    position: 'relative',
    top: 2,
    marginRight: 10,
    fontFamily: Fonts.Poppins_Medium,
  },
  Setwhowintitle: {
    color: Colors.White_text_color,
    fontSize: 15,
    fontFamily: Fonts.Poppins_Medium,
  },
  Flexrowborder: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 13,
    marginBottom: 7,
  },
  Borderone: {
    borderBottomWidth: 1,
    width: widthPercent(28),
    borderBottomColor: Colors.White_text_color,
  },
  Quickbesticonytextstyle: {
    backgroundColor: Colors.Commonheaderlinergradiunttwo,
    borderTopLeftRadius: 10,
    height: 50,
    borderTopRightRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 20,
  },
  Setheightmodal: {
    paddingVertical: SH(20),
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
  },
  Quickbetstyle: {
    color: 'white',
    fontFamily: Fonts.Poppins_Medium,
    fontSize: 18,
    fontWeight: '700',
    position: 'relative',
    left: 15,
  },
  Settextstyle: {
    paddingHorizontal: 10,
    paddingTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  Brentefordtextstyle: {
    fontFamily: Fonts.Poppins_Medium,
    fontSize: 15,
    fontWeight: '700',
    marginTop: -10,
    color: Colors.Commonheaderlinergradiunttwo,
  },
  Setbuttonstyle: {
    backgroundColor: Colors.Gold_text_color,
    width: '20%',
    height: 30,
    paddingVertical: 0,
  },
  Setfootballtext: {
    fontFamily: Fonts.Poppins_Medium,
    fontSize: 15,
    fontWeight: '700',
    color: Colors.Commonheaderlinergradiunt,
  },
  Setfootballtexttwo: {
    fontFamily: Fonts.Poppins_Medium,
    fontSize: 12,
    fontWeight: '700',
    color: Colors.Commonheaderlinergradiunt,
  },
  Setfootballtextthree: {
    fontFamily: Fonts.Poppins_Medium,
    fontSize: 12,
    fontWeight: '700',
    position: 'relative',
    right: 10,
    color: Colors.Commonheaderlinergradiunt,
  },
  Setfootballtextdoigit: {
    fontFamily: Fonts.Poppins_Medium,
    fontSize: 15,
    fontWeight: '700',
    position: 'relative',
    right: 10,
    color: Colors.Commonheaderlinergradiunt,
  },
  Allpadingleft: {
    paddingLeft: 10,
  },
  Flexviewsaetmin: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginRight: 10,
    borderStyle: 'dashed',
    paddingTop: 10,
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: Colors.gray_text_color,
  },
  Setflexview: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  Flexthreedigit: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  Setbgdigit: {
    backgroundColor: Colors.Commonheaderlinergradiunttwo,
    width: 40,
    height: 25,
    borderRadius: 7,
    marginRight: 7,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  Settextstylesimple: {
    color: Colors.White_text_color,
    fontSize: 10,
    fontFamily: Fonts.Poppins_Medium,
  },
  Buttonchnage: {
    backgroundColor: Colors.Gold_text_color,
    width: '48%',
  },
  Buttonchnageteo: {
    backgroundColor: Colors.Commonheaderlinergradiunttwo,
    width: '48%',
  },
  Flexbutton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '96%',
    marginTop: 10,
  },
  ButtonTextStyle: {
    color: Colors.black_text_color,
  },
  ButtonTextStyleto: {
    color: Colors.White_text_color,
  },
  Flexviewretirntext: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
  },
  Centerlastbutton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '97%',
    borderTopWidth: 1,
    borderTopColor: Colors.Commonheaderlinergradiunttwo,
    paddingTop: 17,
    borderStyle: 'dashed',
    marginRight: 20,
    marginTop: 20,
  },
  Firsttextstyle: {
    color: Colors.White_text_color,
    fontSize: 20,
    textAlign: 'center',
    fontFamily: Fonts.Poppins_Medium,
    paddingTop: 7,
    paddingBottom: 5,
  },
  Setfirstblackcolor: {
    backgroundColor: Colors.Commonheaderlinergradiunt,
    width: '70%',
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 20,
  },
  Firsttitlcenter: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 10,
  },
  RocketLonchStyleBox: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  RocketLonchStyle: {
    width: SW(80),
    height: SH(80),
    flexDirection: 'row',
    justifyContent: 'center',
  },
  EarnedTextStyle: {
    fontFamily: Fonts.Poppins_Bold,
    fontSize: SF(21),
    color: '#000',
    textAlign: 'center',
    textTransform: 'uppercase'
  },
  FlexRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dollarAmount: {
    fontFamily: Fonts.Poppins_Bold,
    fontSize: SF(21),
    color: Colors.Gold_text_color,
    marginTop: SH(4)
  },
  dollarIcon: {
    width: SW(25),
    height: SH(25),
    marginLeft: SH(5)
  },
  FlewRow2: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  FlewRow: {
    flexDirection: 'row',
    alignItems: 'center'
  },
  CurrencyBox: {
    justifyContent: 'center',
    backgroundColor: 'lightgreen',
    marginTop: SH(15),
    paddingHorizontal: SH(20),
    borderRadius: 5,   
  },
  CurencyAmount: {
    fontFamily: Fonts.Poppins_Bold,
    fontSize: SH(22),
    color: '#fff',
    marginTop: SH(2),
    marginLeft: SH(5),
    textTransform: 'uppercase'
  },
  IconBackStyle: {
    backgroundColor: 'blue',
    paddingHorizontal: SH(20),
    paddingVertical: SH(10),
    borderRadius: 5
  },
  FlewRow3: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginTop: SH(15)
  }
});